/*
 * randNumberGenerator.cpp
 *
 *  Created on: 15-Dec-2017
 *      Author: rajarshi
 */

#include "randNumberGenerator.h"



/*
 * [Minf, Maxf] is the interval within which the function generated random number
 * of double data type.
 * numrands is the number of random numbers to be generated by the function.
 * Ruturns an array of random numbers in randarray
 */

std::vector<double> randNumberGenerator::getRands(double minf, double maxf, unsigned int n) {

	 distribution = std::uniform_real_distribution<double>(minf,maxf);
	 std::vector<double> numbers(n);

	 for(unsigned int i=0;i<n;i++)
		 numbers[i] = distribution(generator);

	 return numbers;
};

